language: python
env:
  - TOXENV=py27-1.5.x
  - TOXENV=py27-1.6.x
  - TOXENV=py27-1.7.x
  - TOXENV=py33-1.5.x
  - TOXENV=py33-1.6.x
  - TOXENV=py33-1.7.x
  - TOXENV=py34-1.5.x
  - TOXENV=py34-1.6.x
  - TOXENV=py34-1.7.x
install:
  - pip install tox
script:
  - tox